### ISSUE TITLE
Refreshed toolbar updates

### ISSUE THREAD

**Issue by UltrasonicNXT** [Brickimedia/brickimedia#321]
The refreshed toolbar (the one that slides down from the top after you scroll) seems very empty to me. Why have loads more options in a drop down (move, history, etc) when there is loads of white space to fill? The page's title would also make sense in this white space.

**Comment by georgebarnick** [comment]
Icons are planned to go alongside the actions (edit, etc). The title wouldn't fit well. It'd either have to be made smaller text or have the page actions larger, neither of which would be very good. I'd also not like to see it where they fill the whitespace all the way across the screen because that would require me to search through a long horizontal list to find the one I was looking for since I have a very wide monitor (1920x1080).

**Comment by UltrasonicNXT** [comment]
Surely looking along a list is quicker than having to click and then look down a list...?

**Comment by georgebarnick** [comment]
Not when it's a list with no general order to it spread across an entire 24
inch screen. Having "more" there allows for anyone who doesn't see the
action they're looking for in the "main" set of actions to click more
there. Not have to start from point A and read all the way across to point
B. Having an entire list horizontally across the entire screen leaves a
user more likely to not quickly see where the action they're looking for is
at.

**Comment by georgebarnick** [comment]
This is essentially the same concept behind removing Refreshed's second sidebar. Having things centralized in one general area makes things easier to find, navigate and use than having them spread out across the screen.

**Comment by MtMNC** [comment]
Some ideas:
* We could make the toolbar an [OOJS UI toolbar](https://www.mediawiki.org/wiki/OOjs_UI/Toolbars)
* We could combine the header bar (i.e., the one with the logo, dropdowns, etc.) with the toolbar. The content of the unified header/toolbar would change when you scroll down a la [Mashable](http://mashable.com/2015/06/10/lightsail-bill-nye/). Maybe the edit/etc. tools could show up there instead of the header categories like in [the Metrolook skin](https://www.mediawiki.org/wiki/Skin:Metrolook).

What do you think? Any other thoughts?

**Comment by MtMNC** [comment]
(Bump)

**Comment by georgebarnick** [comment]
idk about either of those ideas @MtMNC. The first idea would probably require way too much CSS modification to make it worthwhile. The second idea is kind of cool, but execution wouldn't really work if I interpret your suggestion correctly. You're saying the edit tools and whatnot would appear in the header as one scrolls down, replacing the header categories (which would only be there when you're at the tip of the page?)? If so, there are a couple flaws with that. Firstly, you shouldn't have to scroll to access the edit and other page tool buttons. Secondly, you shouldn't have to scroll back to the top to navigate with header categories. Please correct me if I misinterpreted the suggested execution of that idea.

**Comment by MtMNC** [comment]
@georgebarnick No you're right--on second thought neither one is the best idea. :P The intent was more to get the ball rolling with some ideas if in fact people think redoing the toolbar is a priority. But if it isn't a priority (and tbh I don't think it should be, and based on the lack of responses I'm guessing others feel the same way) then we might as well close this.

**Comment by georgebarnick** [comment]
The only improvements I can see a close need for would be icons beside each action (or at least the primary actions), and perhaps have it detect how wide the window is and have more tools across the bar depending on how wide the screen is.

**Comment by MtMNC** [comment]
@georgebarnick Alright. The icon idea is already a separate issue at https://github.com/Brickimedia/brickimedia/issues/369 (and AFAIK the issue I mentioned there still stands :/), but I think we can work on having the tools leave the dropdown. The question is how many tools should pop out, and at what width? Because I do think the point you made above still stands--if we take too many out of the dropdown, it'll take users longer to find what they're looking for.

**Comment by georgebarnick** [comment]
Maybe have them take up 40% of the content width? That way it's longer but not too long.

**Comment by neoncitylights** [comment]
Brickimedia no longer uses GitHub as an issue tracker.
