### ISSUE TITLE
Make it easier to navigate through Special:ListUsers

### ISSUE THREAD

**Issue by SamanthaNguyen** [Brickimedia/brickimedia#352]
It's so hard to navigate through this page when like 90% of each page is mainly spambots..

![image](https://cloud.githubusercontent.com/assets/4723983/6645169/3367b25c-c988-11e4-8417-2c1d09c31156.png)
![image](https://cloud.githubusercontent.com/assets/4723983/6645172/37980f84-c988-11e4-8ba3-6912813e321b.png)
![image](https://cloud.githubusercontent.com/assets/4723983/6645176/3b21d5fe-c988-11e4-86a1-b67f10e8a446.png)

**Comment by UltrasonicNXT** [comment]
Are you asking to to try and delete spam accounts or change the navigation options?

**Comment by mary-kate** [comment]
Account deletion is a totally separate request and should be discussed separately. IMO it's stupid that MW doesn't offer a clean way to delete users when all kinds of forums and whatnot had that ability over ten years ago; if we could implement a modern version of ``[[Extension:DeleteUser]]``, it'd be spiffy and all, but usually it's easiest just to essentially ignore the blocked spambot accounts.

All that being said, I'll advertise my extension here: https://www.mediawiki.org/wiki/Extension:FilterListUsers
You can see it in action on [Jedipedia](http://fi.starwars.shoutwiki.com/wiki/Toiminnot:Käyttäjät), but we've seriously considered deploying it site-wide because the default [user list view](http://www.shoutwiki.com/wiki/Special:ListUsers) can be outright intimidating for non-power users or people otherwise new to wikis and/or MediaWiki, and especially on a wiki farm setup. People find their way to ListUsers and expect to see a list of users, without realizing that on a farm it means "all users ever registered", not just "users who have made (significant) contributions to this particular site".

**Comment by codyn329** [comment]
Woops, should've replied earlier, but yeah, I like the second extension you suggested. I was thinking of to filter out users who have 0 edits but 5 or less is also good too.

**Comment by mary-kate** [comment]
@codyn329 Technically speaking it's trivial to change the number; right now there's no configuration variable for that, but adding one takes only a few seconds. Why hasn't it been done, then? Mostly laziness on my part (patches welcome etc. ;-).
