### ISSUE TITLE
.lxf/ldr to image converter

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#354]
Is this being worked on? I want to know so if there isn't any or there's very few to try to help on the extension. I think this would be a great extension and would be glad to help push it to get it up and running. =) For the specifics, what kind of programming language are we using to create it?

 Also, if we want to, we could use the same method of when you build a ldd model and submit it to the ldd gallery on ldd.lego.com (where you preview it as an image) and have it published, except modify it if needed.

**Comment by georgebarnick** [comment]
Nobody is currently developing for it, but I'll still be a project manager for it. Also for clarification, this wouldn't be a MediaWiki extension&mdash;it's intended to be a server-side application that works through a command line to input an LXF or LDR, add any paremeters, and output as an image. A MediaWiki extensions could then be utilized to use this command line application for wiki purposes, but first the application needs to be developed itself. This is would be similar to how ImageMagick or GhostScript are used by MediaWiki and extensions to process a file on the server and convert it for MediaWiki.

**Comment by UltrasonicNXT** [comment]
It's not as simple as just converting it to an image. You need to specify viewing angles and so on... It's more rendering a model, not just converting to an image

**Comment by georgebarnick** [comment]
@UltrasonicNXT: As I said "add any paremeters" as the second step. :)

**Comment by codyn329** [comment]
I believe something like [@Tribex/LDRParser](https://github.com/Tribex/LDRParser) is similar to what we're aiming for.

**Comment by Tribex** [comment]
@codyn329 The goal of this project is to take a LDR model as input, then output an image, correct? For such a project, you would need a renderer of some sort and a converter from LDR files to that renderer's native format. I believe [LDView](http://ldview.sourceforge.net/) supports [POV-Ray](http://povray.org/), but I don't think it has a command-line based converter. 

An interesting idea, though likely impractical due to the amount of data transfer needed would be to use @Tribex/LDRParser to send the raw JSON format, then parse it on the client using JavaScript and WebGL (through THREE.js or BabylonJS) to display a 3D model, which could then be interacted with by the user. However, the JSON files generated by LDRParser can grow to quite a few MBs.

**Comment by codynguyen1116** [comment]
I don't think this is something that's been requested a lot (currently, from what I know) so I put it at the Q1 2017 milestone along with a label but it would be very interesting to see it made sometime this year or by the end of the next march :+1:

**Comment by codynguyen1116** [comment]
question answered so I'm closing
