### ISSUE TITLE
Hitting "reply" on comments extension goes to wrong place

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#357]
In a comments section, when you hit "reply" on any of the comments, it jumps you to the bottom of the page instead of to the area where the comments box is located.

**Comment by mary-kate** [comment]
This is the intended behavior, because on a more vanilla install of MW + Comments, the comment box is located at the bottom of the page: http://social-tools.wmflabs.org/wiki/Talk:Main_Page .
I'm not sure why it is located where it is on Brickimedia or what code is responsible for that, but maybe @UltrasonicNXT would be able to shed more light on this matter? (Also, the "socialprofile" label is _technically_ incorrect since Comments is an entirely separate extension that can be used without SocialProfile, but alas, we don't have a label for the Comments ext., at least yet...maybe such a label should be created.)

**Comment by georgebarnick** [comment]
Brickimedia is on a vanilla install of MW, and I'm fairly certain we've been on a vanilla install of Comments for several months.

And the socialprofile label is being used for practically any social tool right now, so this fits in there.

**Comment by UltrasonicNXT** [comment]
Patch submitted: https://gerrit.wikimedia.org/r/#/c/200155/

**Comment by UltrasonicNXT** [comment]
Done.
