### ISSUE TITLE
Wikilove link in dropdown menu is broken in Refreshed 3.*

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#361]
(Minor issue, although just wanted to point it out since I saw this issue today)

So, it doesn't work while it's on this menu...

![image](https://cloud.githubusercontent.com/assets/4723983/6881679/13f73a6c-d538-11e4-920b-18eafb69e806.png)

But it does when you scroll down 

![image](https://cloud.githubusercontent.com/assets/4723983/6881683/3316c7dc-d538-11e4-846f-332321185877.png)
![image](https://cloud.githubusercontent.com/assets/4723983/6881684/40f3df84-d538-11e4-8388-d0e24ffe7401.png)

**Comment by MtMNC** [comment]
I'm guessing the WikiLove dialog appears when the li tag with id ca-wikilove is clicked, but since there's two of them it goes for the one further down in the HTML, which happens to be the one in the scrolling toolbar. Honestly it might be easier to have only one toolbar that sticks to the top of the window when you scroll down; thoughts?

**Comment by MtMNC** [comment]
Looks like this has been fixed as of https://github.com/Brickimedia/Refreshed/commit/dc0f87ced5fa0c62a0b8f9e5280dd1be1089e810.
