### ISSUE TITLE
500 server error on Special:SpecialPages at Meta

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#372]
__Edit__: New screenshot of what it currently looks like:

![image](https://cloud.githubusercontent.com/assets/4723983/12222175/1798e272-b77a-11e5-928b-c2a82ce15dc4.png)

This page is the only one on Meta that seems to give a 502 Bad Gateway error, not sure why (also tested Special:SpecialPages on the other wikis, which seem to work)
![image](https://cloud.githubusercontent.com/assets/4723983/7106233/b56e02f4-e0ff-11e4-9744-37eac50febb3.png)

**Comment by mary-kate** [comment]
Ping @UltrasonicNXT -- could you take a look at this? MultiUpload is being its lovely, stupid self, once again:
``
2015/04/15 21:48:00 [error] 8746#0: *1790976 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare class SpecialMultiUpload in /var/www/core/extensions/MultiUpload/SpecialMultiUpload.php on line 120" while reading response header from upstream, client: [removed my IP], server: *.brickimedia.org, request: "GET /wiki/Special:SpecialPages HTTP/1.1", upstream: "fastcgi://unix:/tmp/php5-fpm.sock:", host: "meta.brickimedia.org", referrer: "http://meta.brickimedia.org/wiki/Main_Page"
``

MultiUpload's current iteration supports old, outright ancient MediaWikis (all the way to...1.20.x or even 1.19.x?) "by design", and as such, it does some scary voodoo with `$wgAutoloadLocalClasses` in the aforementioned file; MultiUpload's maintainers come and go but no-one's really looking after that extension, despite it being relatively popular and used on many sites (but not on Wikimedia wikis, which somewhat explains the lack of a proper maintainer).

**Comment by UltrasonicNXT** [comment]
ah I found this error a little while ago and got stumped, asked Lewis and he wasn't sure either. Looking at that file now, eurrrggghhh

**Comment by codynguyen1116** [comment]
Fixed since MultiUpload was uninstalled in https://github.com/Brickimedia/LocalSettings/commit/b23d5fe14efa7fb138e8ef2b339ea2a5fa62e36c
