### ISSUE TITLE
Rebrickable API integration with Brickipedia

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#374]
This is just an idea, but using the Rebrickable API (from what I know) could mean that'd it'd be a lot easier to generate inventories for sets, compared to manually creating them. The source is located at: http://rebrickable.com/api/

**Comment by georgebarnick** [comment]
Rebrickable inventories are generated both manually and from LEGO.com and Brickset (Brickset also getting theirs from LEGO.com). For this matter, we already are doing the same work, and since Brickipedia is a wiki, it's right for our content to be user-generated (otherwise we can't accurately call ourselves a collaborative encyclopedia as we won't be building our own content).

Other issues with this are that Rebrickablle uses Peeron and Bricklink IDs for some of its parts entries, whereas we don't necessarily use the same numbering in all instances. On the other hand, there are also instances where Brickipedia uses Bricklink or Peeron IDs where Rebrickable will be using official LEGO design IDs. There's also the issue of set numbering. Rebrickable follows set numbering based on Brickset, which is done by the official LEGO product number followed by an identifying number for when multiple sets share the same number (e.g. "10500-1"), whereas at Brickipedia that identifying number isn't present. For that reason, any set, such as "10500-2" on Brickset, will simply be "10500" on Brickipedia. This can create incorrect matches if we were to associate our pages with Rebrickable items, leading to various potential issues. The only way to associate a Brickset number and a Brickipedia title automatically is with Brickipedia's Snippet API queried to the set number, which still is not perfectly accurate, because a query for "10500" on Brickipedia could also turn up "Part:10500" for example.

All in all, this won't work. It isn't feasible, and it goes against Brickipedia's mission, therefore isn't worth pursuing as a possibility.

**Comment by codyn329** [comment]
OK, thanks for the answer - All of it makes sense so I'll close this
