### ISSUE TITLE
Comment pagination doesn't work

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#375]
So, for the first time, we've reached [a page](http://en.brickimedia.org/wiki/Brickipedia:Pick_the_Hero_contest)  that has over 100 comments, and it looks like comments are meant to be paginated every 100 comments (a little 1 2 > has popped up). However, nomatter what you click, it seems to bring up the oldest 100 comments. I thinking it might have to do with the descending sort order of the comments that wasn't originally in the extension?

**Comment by georgebarnick** [comment]
I can confirm this as an issue for me as well

**Comment by UltrasonicNXT** [comment]
Okay the comments paging system needs a lot of work. Even ignoring this bug I've found a couple of other problems with it

**Comment by UltrasonicNXT** [comment]
@mary-kate opinions on removing the sort by vote option? It kindof doesn't make sense, as if a reply is one of the highest, it would be out of context without showing the parent comment and previous replies, but then those clog up the list...

**Comment by mary-kate** [comment]
@UltrasonicNXT Well, Ars Technica comes to mind (even though it's not MW-based) -- the commenting section is located at the bottom of the article, initially hidden, save for one "highlighted" comment; I don't know how it's chosen, I believe it's not the comment with the most votes but the one deemed somehow "interesting" enough by Ars staff. Slashdot (again not a MW-based site) hides comments which have a low voting score by default and only shows the ones with a high(er) score by default; especially true for popular stories with lots of comments and thus lots of votes. The open-source [Commentics commenting system](http://www.commentics.org/) allows to sort comments by time, comment rating and overall "thread" rating (I guess?).
In light of this, I'd propose keeping the "sort by vote" option, _if possible_. If you feel that fixing it would take up an insane amount of time and energy or that it's just broken by design, then feel free to remove it; I'm not saying that you can't ever drop features. :)

(Admittedly making this decision would be somewhat easier if we had statistics showing how many people actively use that feature, but alas...and obviously gathering such usage stats would take a long time, so it's not really a feasible option.)

**Comment by georgebarnick** [comment]
FWIW I don't think I've ever used the non-default sort orders, and can't imagine me doing so. The default sorting in chronological order just makes the most sense in all situations on a wiki I can think of.

**Comment by UltrasonicNXT** [comment]
Actually maybe I'll just leave it there for the mo

**Comment by UltrasonicNXT** [comment]
If you think of social media/popular blog sites that just get way too many comments to show them all, I guess it's then when you need the sorting. I've found a low cost way to leave it there, so we'll keep it for the mo.

**Comment by georgebarnick** [comment]
Note- the page linked to in the original post no longer has the issue as it has less than 100 comments now. For debugging (for those without their own debugging setup), I've made 101 comments to http://dev.brickimedia.org/wiki/Comments to replicate the issue.

**Comment by UltrasonicNXT** [comment]
Finally got around to submitting this: https://gerrit.wikimedia.org/r/#/c/210390/

**Comment by UltrasonicNXT** [comment]
Hmm, it's working on loading the page, but on trying to switch to another page of comments it fails. The errors in the log are ```PHP Fatal error:  Call to a member function getIsPreview() on a non-object in /var/www/core/extensions/PageInCat/PageInCat_body.php on line 280``` though

**Comment by mary-kate** [comment]
Yeah, I've seen that one a few times before on the error log. Could probably try error_log(print_r())'ing the $parser variable and seeing what it is...maybe Comments could also somehow set the config global `$wgPageInCatUseAccuratePreview` to `false`? A hacky fix, but it should work.
I strongly suggest filing a ticket on Phabricator about this, since PageInCat's original author (bawolff) is still around and very much active, so he should be able to help out with this issue, I hope.

**Comment by UltrasonicNXT** [comment]
Oh, no longer getting that error.

**Comment by UltrasonicNXT** [comment]
This is fixed then, that page on dev is working fine. If that thing with PageInCat crops up again it can have a new issue,
