### ISSUE TITLE
Ratings not showing up in refreshed

### ISSUE THREAD

**Issue by Brickfilmer** [Brickimedia/brickimedia#380]
I always use Vector, where Ratings still work fine, so I didn't really notice it until Mr. Bimple brought it up. Basically, in Refreshed, article ratings do not seem to appear, somehow being cut off by another portion of the page. On pages like http://en.brickimedia.org/wiki/M-Tron, where the rating tag is at the very top of the article, there is no way at all to make the rating show up on the page. However, on pages such as http://en.brickimedia.org/wiki/Part:60474, where the {{Partnames}} template precedes the "rating" tag , the rating will show up if you narrow the window, though it'll then be partially cut off by said {{Partnames}} template.

**Comment by codyn329** [comment]
Removing the css declaration ```margin-right: 45px;``` from the class ```.mw-rating-tag``` seems to work. Not sure where the css source is though..

**Comment by NovaFlare** [comment]
I believe it may be a problem with [the main JS file] (http://en.brickimedia.org/wiki/MediaWiki:Common.js)- it's referring to class names which don't seem to exist, like #maintitle. I tried changing it to #firstHeading, but it didn't seem to make a difference, that could be due to the awful caching on the site with things like this though.

**Comment by codynguyen1116** [comment]
Not an issue anymore, so closing
