### ISSUE TITLE
Server has crashed again

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#402]
Constantly getting hit by error 502's and 504's and unable to get onto the site. Last time Meiko said it was a one-line fix and it should work after that for a couple of months, I don't know what the code is though.

(And is there any chance of getting this fixed permanently?)

**Comment by codyn329** [comment]
Im guessing that since there might be too much stress on the server from loading so many pages, there would have to be a server upgrade. I have no idea of what our financial stance is though, but if you happen to know that'd be great. Otherwise, you'd have to ask Ajraddatz since he handles that.

**Comment by NovaFlare** [comment]
Why couldn't I ever find those pages? :P

We could definitely do that first suggestion (set $smwgQEqualitySupport to SMW_EQ_NONE) which is meant to give "drastic" search improvments. If the site ever comes back, I can take a look at that LUA-based templates suggestion too- most of the problems I'm guessing are described in the "slow query formatting" area.

But... yeah... we could really do with that temporary fix right about now... @georgebarnick @Ajraddatz ...

**Comment by codyn329** [comment]
I took a look at Lua, and the major downside I found is that its not very user friendly. :/ A Wiki is a site where everyone can edit, and this doesn't ring true to this Lua language. First off, lets look at this documentation: https://www.mediawiki.org/wiki/Extension:Scribunto/Lua_reference_manual
There is a *lot* to learn and cover, which is definitely not an exaggeration. Being realistic, there's a low chance for the users to take their time and learn a whole new programming language. Oh, and you'd have to take the time to convert the templates from wikitext to Lua too, since it's not done automatically. Here's an example of a Lua module: https://www.mediawiki.org/wiki/Module:Message_box

And now, I can't really tell if this version is even faster, because on  https://www.mediawiki.org/wiki/Lua_scripting, it directly says "*complex templates have caused performance issues and bottlenecks.*" This contradicts whats said on the smw page, which is a bit confusing.
