### ISSUE TITLE
Drop support for IE8 and older

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#407]
Refreshed is quite broken in IE8 and older, and I believe some of our other proprietary extensions have issues with it as well. Are there any oppositions to <i>officially</i> dropping support for it in our extensions? Of course we can always still have things work in it, but we shouldn't go out of our way nor focus on compatibility anymore I don't think. Google Analytics, although wildly inaccurate for our site's tracking (we favor Quantcast, but Quantcast doesn't track user technology to my knowledge), indicates that IE8 is not widely used by our site's visitors, and IE9 and IE10 are used more frequently than IE8. If there are any oppositions to officially dropping support for IE8, let's discuss it in the comments. Otherwise I'd like to indicate on Refreshed's skin article on MediaWiki.org that we don't intend to support IE8 anymore.

**Comment by codyn329** [comment]
Sounds like a great idea :P I never really liked IE 8 anyways

**Comment by MtMNC** [comment]
Yeah I'm down.

**Comment by UltrasonicNXT** [comment]
Sure. Out of curiosity, do your analytics give a percentage of users that use IE8?

**Comment by georgebarnick** [comment]
@UltrasonicNXT: You have access to the same analytics I do. No.

**Comment by mary-kate** [comment]
Of course it depends on what you're trying to do; a lot of things will work on IE8 just fine without additional adjustments. Refreshed, for example, is a complex, modern, responsive skin that uses some advanced techniques which are simply not supported by IE8. IE8 is an old browser, essentially the IE6 of our age -- due to the amount of people using Windows XP and IE8 being the last version of IE for XP.

Addressing all the quirks of older IEs is simply put a pain, and while I don't _like_ it, it would make sense to drop IE8 support. Maybe we could detect IE8 users and advice them to either upgrade their browser (if they're **not** on XP) or download something like [Firefox Portable](http://portableapps.com/apps/internet/firefox_portable), which allows XP users to use a recent build of Firefox from a USB device (in case if you don't have admin rights on the XP box -- think of schools, universities, businesses, ...).

**tl,dr:** No objections to dropping support for IE8, though it could be nice to display the affected users a banner to let them know what's going on and what they should do to view the site correctly.

**Comment by MtMNC** [comment]
As of https://github.com/Brickimedia/Refreshed/commit/5132607ee4e42173d9e0cdaab9fb6ee9f8059be5, Refreshed uses HTML5 semantic elements, which aren't supported in IE8--for all intents and purposes we've dropped support. Closing....
