### ISSUE TITLE
XSS vulnerabilities in EmbedVideo

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#412]
In Brickimedia/extensions@c87a14b (ATTN: @UltrasonicNXT), <a href="https://www.mediawiki.org/wiki/Extension:EmbedVideo">EmbedVideo</a> was reverted from version 2.2.5 to version 2.2.1, which has opened up XSS vulnerabilities that were patched in EmbedVideo 2.2.5. If our PHP version (5.3.29) prevents us from updating EmbedVideo, I'd suggest we work towards updating our PHP version rather than leaving security flaws present on our site.

**Comment by mary-kate** [comment]
It should be mentioned that PHP 5.3 reached its [end-of-life (EOL)](http://php.net/eol.php) a year ago. That being said, sometimes upgrading is indeed a pain and easier said than done.

As for EmbedVideo, judging by a quick glance through its sources (I assume we're talking about [this version](https://github.com/Alexia/mediawiki-embedvideo)), it doesn't seem to be using any "real" PHP 5.4+ features, just the short array syntax (`[]`, as opposed to the traditional `array()`).
(Temporarily) forking the extension and converting those usages manually back to the older, more standard syntax should be easy enough to do, even if rather tedious, and it'd allow to maintain PHP 5.3 for the time being while running EmbedVideo version 2.2.5.

We should be researching into video usage, and questions such as:
* where videos are used?
* from what service(s) are videos embedded? (I'd guess the most common answer to this is "YouTube", but you never know)

Depending on the answers, we might want to consider an alternative video extension. ShoutWiki uses [Wikia's old YouTube extension](https://www.mediawiki.org/wiki/Extension:YouTube), which, despite its name, supports also some other video embedding service. There's also the more "social" [Extension:Video](https://www.mediawiki.org/wiki/Extension:Video), which has been a perpetual work-in-progress since 2007 or so (contributions are welcome ;-).

**Comment by georgebarnick** [comment]
We just transitioned all our videos on all wikis from VideoFlash to EmbedVideo. I'd like to stick with EmbedVideo for now.

**Comment by UltrasonicNXT** [comment]
We're on EmbedVideo 2.2.8 now
