### ISSUE TITLE
User blog pages are thinner when not signed in

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#421]
User blog pages width are thinner when not signed in, not sure if this is intentional or not, but the width should take up the whole page. 

![image](https://cloud.githubusercontent.com/assets/4723983/11768418/ebb75812-a191-11e5-96ed-52c7cb7fcc6d.png)
![image](https://cloud.githubusercontent.com/assets/4723983/11768416/e31b4fa6-a191-11e5-80bb-80e92b531453.png)

**Comment by mary-kate** [comment]
[Brickimedia's own MediaWiki:Global.css](http://meta.brickimedia.org/wiki/MediaWiki:Global.css) has the rule `.full { width: 100%; }` which makes top-level comments as wide as the actual page (instead of the default 530px). For whatever reason, it doesn't appear that this CSS page is loaded for anons, so they get the usual default of 530px instead [(from `/extensions/Comments/Comments.css`)](https://github.com/wikimedia/mediawiki-extensions-Comments/blob/master/Comments.css).

530px sounds like a rather bad default for a variety of reasons, including, but not limited to the fact that it uses a pixel-based fixed width rather than a percentage-based, more responsive width. Alas, making the [Comments extension](https://www.mediawiki.org/wiki/Extension:Comments) more responsive is tricky.

For reference: [upstream ticket #T106268](https://phabricator.wikimedia.org/T106268) about making social tools more responsive.

**Comment by codynguyen1116** [comment]
closing per https://github.com/Brickimedia/brickimedia/issues/421
