### ISSUE TITLE
Site CSS/JS won't update

### ISSUE THREAD

**Issue by MtMNC** [Brickimedia/brickimedia#424]
@lewiscawte @UltrasonicNXT

As @georgebarnick mentioned in https://github.com/Brickimedia/brickimedia/issues/420#issuecomment-159991949, changes made to MediaWiki:*.(css|js) pages don't appear on site. This is confirmed to be an issue on enbricki and GBC, but it works fine on dev; unsure about the other wikis. Until this issue is resolved we can't make CSS-breaking changes to the skin, so no progress can be made on skin development until this issue is resolved.

**Comment by UltrasonicNXT** [comment]
I have no clue why, or how to fix.

**Comment by MtMNC** [comment]
Hey actually it worked! It just took quite a long time for the changes to actually take effect. Closing (for now at least)....

**Comment by georgebarnick** [comment]
Weird it didn't have an issue on dev. @UltrasonicNXT to your knowledge is devwiki configured differently caching-wise?

**Comment by lewiscawte** [comment]
Dev.brickimedia.org doesn't go through CloudFlare, because it's a dev site for testing things. It should have next to no traffic other than when a testing is being run, and even that testing is normally low load as compared to the extensive processing needed for each request to a site like Brickipedia.
