### ISSUE TITLE
Improve header UX

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#434]
The header looks great, but I think the UX part could be improved by just changing some minor things. I would make a pull request but UX is subjective and is better when there's user feedback (because that's the point of UX) and discussion, so thus an issue has spawned!

# Search
 - [x] The search box's placeholder text color is around ```#eee``` while the background is ```#fff``` (white), and not only that the typeface is very thin. The font weight should be bold and with a darker text color.
 - [ ] __*possibly* minor issue__: Since the search box is smaller compared to most of the other stuff on the other page and all the things on the header are white, it should contain a magnifying glass icon so it's more noticeable. Plus not all users know pressing enter is an option. 

# Drop down menus
- [ ] Animations on the drop down menu aren't being used correctly. Instead of fading in on click and out, it should just be a slide from the top to bottom position, and bottom to top position when clicked out. __Example__: http://callmenick.com/post/slide-down-menu-with-jquery-and-css
- [x] When clicking on button that triggers a drop down menu, the other drop down menus should close to avoid overlap and cluttering.
- [x] The names "Brickipedia" and "Brickimedia" are too similar, and their logos are similar which can lead to a miss-click to the wrong site. Their logos are also very similar but...
    * __The problem is__: The logos and name have lasted for so long that they're ingrained into the user, so changing it would take time to rebuild recognition between the logo and the user. 
    * __Possible solution__: Change position between "Brickipedia" and "Brickimedia" on the drop down list so they aren't as close to each other and will lead to less confusion.
- [ ] The text on the sub-items of the list are too squished together, which decreases readability and increases miss-clicks, so increase the margin between them
- [x] Clicking on the drop down menu box is possible, but the sub-menu item boxes aren't clickable and only clickable via the text. They should be ```displayed``` as ```blocks``` (```display:block;```)
- [x] Close drop down menu after clicking outside of it (suggestion by **George Barnick**)

**Comment by georgebarnick** [comment]
Good draft and very good points. I sense a future project manager in you. :smiley: UX has always been my primary concern when directing development for it especially with the Refreshed 3.* update. That doesn't mean it's perfect and you've brought up some good improvements. Patching the dropdowns to slide instead of fade would be a good step to take in the next Refreshed patch. Your point about "Brickipedia" and "Brickimedia" is acknowledged and Brickimedia on its own is confusing to many people who just know "Brickipedia". I suggest Brickimedia Meta be reanamed to "Meta Brickimedia", putting Meta first of course and using the word Meta for the logo. Most community members already refer to it as simply Meta, so this shouldn't be too difficult for them to adjust, and can lead to less confusion for unfamiliar new users and visitors.

**Comment by codynguyen1116** [comment]
Haha thank you :) I also believe UX is an important factor and should be considered more often. I like your idea of changing it to Meta and that it will make sense to users :+1: I'll try to find more things that can be improved

**Comment by georgebarnick** [comment]
If you're able to patch the sliding dropdowns that would be great to do soon

**Comment by MtMNC** [comment]
Good stuff. Some quick observations:
>Animations on the drop down menu aren't being used correctly. Instead of fading in on click and out, it should just be a slide from the top to bottom position, and bottom to top position when clicked out. Example: http://callmenick.com/post/slide-down-menu-with-jquery-and-css

The author of that article recommends using jQuery's slide functions, which should be easy to implement. That said, jQuery also has built-in fade in and out animations but CSS is a lot better for those performance wise, so maybe it's the same with slideToggle(). Either way, should be simple. I'd recommend classes similar to the `.fadable` and `.faded` ones we have already (`.slidable` and `.slided`? `.slid`? :P) that changes height instead of opacity. Or even the dropdowns could have both fade and slide animations.

>When clicking on button that triggers a drop down menu, the other drop down menus should close to avoid overlap and cluttering.

Thought I got it to work on my local clone as of the latest commits, but looking back I guess not. :/ I'll try and fix it this weekend (if not sooner).

>The text on the sub-items of the list are too squished together, which decreases readability and increases miss-clicks, so increase the margin between them

They used to be larger, weird. Good catch. Probably got messed up somewhere in one of the mass element renames. I'll look into it.

>The names "Brickipedia" and "Brickimedia" are too similar, and their logos are similar which can lead to a miss-click to the wrong site. Their logos are also very similar but...

Agreed. In addition to what @georgebarnick suggested above, something to consider would be creating textless (that's a word I guess :P) logos for all wikis. The logos in the dropdown could then have an image and a text component, which might make it less confusing. Also, the images could be used for the mobile header

**Comment by georgebarnick** [comment]
Another UX improvement to add to this is that when clicking anywhere outside of a dropdown, such as in ```#content``` for example, it should collapse the dropdowns that are open. I'm fairly certain they used to do this but recent patches might have removed that, and it was a good UX feature. On any site where I find myself using dropdowns or popup menus, it's more natural to be able to click outside of the box to collapse/dismiss it. Having to move the mouse back to the source shouldn't be entirely necessary.

@MtMNC: For textless logos, we'd need to have someone design something new for Meta or Brickipedia. Both use a red 2x2 LEGO brick graphic currently.

**Comment by codynguyen1116** [comment]
Good points there, I think slid is better since technically (English is an odd language :P), slided isn't a word and slid is, although both look a little funky TBH. There was also a JS vs CSS animation article on CSS-Tricks that I read which (I think)said JS is actually better in the performance area, I'll have to find it later

As for textless logos are we thinking of favicons/symbols? Customs happens to have the same symbol actually but it could be changed so that each stud on the 2x2 brick is a different color, if we do want to continue with the brick concept. (We should also considering expanding favicons support through OSs with meta tags and different image proportions but what's more important is if we were to redesign what they'd look like and still make sense)

**Comment by codynguyen1116** [comment]
Adding to my above comment @MtMNC there *are* mobile logos but no mobile logo drop downs

**Comment by MtMNC** [comment]
@codynguyen1116 The whole idea of a "slide down menu" doesn't really make sense--they're not sliding, they're expanding! (At least with the jQuery function.) :P Oh well. And I'd be interested in seeing that CSS-Tricks article if you have it still--JS could very well be the better solution! I said CSS was more efficient that based on my perceived smoothness of the animation rather than any hard metrics, but maybe there's more at play there.

As for "mobile logos" I wasn't thinking of favicons specifically, but certainly said logos could be used as favicons as well. As of https://github.com/Brickimedia/Refreshed/commit/56f5385779879e049a3466be3e9528c0371de88d,  `$wgRefreshedHeader[‘mobileimg’]` can be set in LocalSettings.php so that a custom image linking to the homepage appears just to the right of the hamburger icon. This icon only appears on the small version of the site. None of the wikis use it currently. That's in addition to the current logo tucked away in the sidebar, which all the wikis do have.

As you mentioned, better interwiki navigation is another UX improvement that should be made. Currently  https://github.com/Brickimedia/brickimedia/issues/371 is dedicated to that... should we close that issue in favor of this one? It might be good to centralize everything.

**Comment by georgebarnick** [comment]
@MtMNC: Let's keep that open and direct efforts towards interwiki navigation there, and keep this for other UX topics and planning.

**Comment by codynguyen1116** [comment]
Here's the article I promised! https://css-tricks.com/myth-busting-css-animations-vs-javascript/ very interesting to read, from reading this I suggest we use JS instead.

**Comment by codynguyen1116** [comment]
Updated the top comment into to do list so it's easier to keep track of everything.

 **Notes**: I'm marking the placeholder task to be done later since the pseudo-element ```::placeholder``` is poorly supported across web-browsers and the vendor prefixes aren't ready to be used on public production sites. The only other related psuedo-element is ```::placeholder-shown``` but it's not for styling the text itself of the placeholder. Also tested with the following code on Brickimedia and it didn't work:

```css
#searchInput::-moz-placeholder,
#searchInput::-webkit-input-placeholder,
#searchInput:-ms-input-placeholder {
	color: #000;
	font-weight: bold;
}
```
References below:

* ```::placeholder``` web browser support: http://caniuse.com/#feat=css-placeholder
* ```::placeholder-shown``` web browser support: http://caniuse.com/#search=placeholder-shown
* ```:-ms-input-placeholder``` - https://msdn.microsoft.com/library/hh772745(v=vs.85).aspx
* ```::-mz-placeholder``` - https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-placeholder

**Comment by codynguyen1116** [comment]
So the whole placeholder section I just wrote was mostly wrong so I decided it'd be easier to just **rewrite** the whole thing. :P Please ignore that whole section up above!

So, placeholders actually do have *mild* browser support, what I figured out what I did wrong with the code I wrote up above is that I grouped them together, and if one selector is wrong then the whole group is parsed as invalid (because of different browser engines). Individualizing them works:

```css
#searchInput::-webkit-input-placeholder {
	color: grey;
	font-weight: 700;
}

#searchInput::-moz-placeholder {
	color: grey;
	font-weight: 700;
}

#searchInput::-ms-input-placeholder {
	color: grey;
	font-weight: 700;
}
```

There's still a problem with this though, which is the ```::-ms-input-placeholder``` pseudo-element's backward compatibility only goes to IE 10, and our official stance is to support all the way back to IE 9. This means that the code up above will *not* work for IE9 users. Is there something we can do to fix that problem (other than write dirty hacks?) 

(also hopefully one day our code can look like this)
```css
#searchInput::placeholder {
	color: grey;
	font-weight: 700;
}
```

**Comment by georgebarnick** [comment]
Here's an SVG Meta logo. Lemme know what you think.

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 330.3 126.4">
  <style>
    .brick0{fill:#00AA00;} .brick1{fill:#FF0000;} .brick2{fill:#FFB600;} .brick3{fill:#0000FF;}
  </style>
  <path d="M74.2 100.4V70c0-11.1-4.2-14.1-10.4-14.1-7.4 0-11.2 4-11.2 17.2v27.3H39.3V70c0-10.9-3.8-14.1-10.8-14.1-7.7 0-10.8 4.1-10.8 17.2v27.3H4.4V45h12.2v5.2c3.9-4.7 7.9-6.5 14.4-6.5 7.6 0 12.5 2.6 16.3 8.6 4.5-6 10-8.6 17.8-8.6 14.6 0 22.4 8.1 22.4 24.7v32H74.2zm79.1-21.8h-42.9c1.6 6.7 7.4 10.9 15.3 10.9 5.5 0 8.8-1.5 12.2-5.5h14.5c-3.7 11.4-15.2 17.7-26.4 17.7-16.9 0-30-12.6-30-28.8 0-16.3 12.9-29.2 29.2-29.2 16.5 0 28.6 12.6 28.6 29.8 0 2-.1 3.2-.5 5.1zm-27.9-22.7c-7.9 0-13.3 3.9-15.4 11h30.7c-1.7-7.1-7.1-11-15.3-11zm52.3 1.2v43.3h-13.3V57.1h-6.5V45h6.5V26.5h13.3V45h8v12.1h-8zm57.6 43.3v-7.2c-5.3 6-10.6 8.5-18.4 8.5-16.2 0-27.9-12.1-27.9-28.8 0-16.9 11.8-29.2 28.2-29.2 8 0 13.5 2.6 18.1 8.7V45h12.2v55.4h-12.2zm-16.7-44.5c-9.5 0-16.2 7.2-16.2 17.3 0 9.7 6.7 16.3 16.4 16.3 10.1 0 16.1-7.2 16.1-16.4 0-10.1-6.8-17.2-16.3-17.2z"/>
  <g id="g3934">
    <path id="path3909" class="brick0" d="M198.652 75.32h-10v5h-10v-5h-10v5h-5v20h40v-20h-5v-5z"/>
  </g>
  <g id="g3930">
    <path id="path3913" class="brick1" d="M279.752 75.32v5h-10v-5h-10v5h-5v20h40v-20h-5v-5h-10z"/>
    <path id="path3915" class="brick2" d="M320.752 74.12l-4.2 2.7-5.4-8.4 4.2-2.7-5.4-8.4-4.2 2.7-2.7-4.2-16.8 10.9 21.8 33.5 16.8-10.9-2.7-4.2 4.2-2.7-5.6-8.3z"/>
  </g>
  <path id="path3911" class="brick3" d="M82.6 20.2L80 24.5l-4.3-2.6-10.5 17 34 21 10.5-17-4.3-2.6L108 36l-8.5-5.3L97 35l-8.5-5.3 2.6-4.3-8.5-5.2z"/>
</svg>
```

PNG raster @ 300ppi:
![meta logo](https://cloud.githubusercontent.com/assets/3800972/12310707/bb6d90ee-ba1f-11e5-9f89-c340b862a1cb.png)

As for Customs, I don't think we should rename it. Talk's been to rebrand it as a new wiki and consume Stories into the new wiki's scope. New name can be decided. This forum needs some expediting and be completed already: http://meta.brickimedia.org/wiki/Forum:Merging_wikis

**Comment by codynguyen1116** [comment]
This looks great! Also when you mentioned that (I completely forgot about Stories to be honest), I agree. I'll add my comments to the forum later this week.

**Comment by MtMNC** [comment]
(Closed automatically because of how the commit was worded, sorry)

**Comment by codynguyen1116** [comment]
Great job guys, we're already half way done. :D Good progress :+1: I'll fix the search icon issue, the squished sub-menu items, and clicking on sub-menu items issue and then I'll focus on the animation issue if I have time.

**Comment by codynguyen1116** [comment]
The wordmark logo should be reflected for the DeepSea logo of Meta also, since some users still use it too and we should aim for visual consistency, it shouldn't take that long to fix. @georgebarnick and @MtMNC

**Comment by MtMNC** [comment]
Don't have commit rights to DeepSea I'm afraid. @NovaFlare could you do it?

**Comment by codynguyen1116** [comment]
@MtMNC No worries, you don't require access to any of the repos. In https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings_meta.php, the wgLogo variable is set to http://images.brickimedia.org/thumb/a/ab/Brickimedia-logo.png/150px-Brickimedia-logo.png, so all you need to do is reupload a new version at [Special:Upload](http://meta.brickimedia.org/wiki/Special:Upload).

**Comment by codynguyen1116** [comment]
@MtMNC any update on that DeepSea logo?

**Comment by MtMNC** [comment]
Oh man, forgot about this. Sorry to hold things up.

...And apparently I don't have commit rights there either. :P @mary-kate could you change the logo?

**Comment by codynguyen1116** [comment]
No MtMNC you just need to design a logo and upload a new version at meta! :P you don't need rights

**Comment by MtMNC** [comment]
Lolol wow I'm on my game huh? This is what I get for skimming over things :P Doing it right now

**Comment by MtMNC** [comment]
Done. Sorry!

**Comment by codynguyen1116** [comment]
No problem, thanks for doing it :+1:

**Comment by codynguyen1116** [comment]
https://phabricator.wikimedia.org/T136527
