### ISSUE TITLE
GBC Wiki UI error

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#436]
I was scrolling through meta, and I saw someone uploaded this image:

![image](http://images.brickimedia.org/1/13/GBC_Site_Error_when_Logging_in_mainpage_Screenshot_2016-01-17_10.53.53.png)

(source: 
http://meta.brickimedia.org/wiki/File:GBC_Site_Error_when_Logging_in_mainpage_Screenshot_2016-01-17_10.53.53.png)

From what's been given through the screenshot: the MW skin is Refreshed, the browser being used is Chrome,  although I don't know what version nor the OS. I've asked the uploader ([Mjsweet](http://meta.brickimedia.org/wiki/User_talk:Mjsweet)) for more information and he/she hasn't responded yet although this is still an issue that should be fixed.

**Comment by codynguyen1116** [comment]
__UPDATE:__ I realized this issue relates to #425, meaning that the browser and OS doesn't matter in this situation. It's been said it'd resolve itself in about a week and it's been a week, however it's still a problem. I suggest #425 should be reopened and to be given more focus.

**Comment by MtMNC** [comment]
~~I noticed this one when the PHP was cached a while ago, but it's resolved itself for me at least. There are some other CSS problems (e.g., hamburger icon background is the wrong color) but I think that's an issue with local CSS (to be fixed by the site) rather than one with Refreshed.~~

~~Here's a screenshot (logged out, which is where the PHP was broken before). Could you post a screenshot so we could see what other UI issues there might be?~~

Actually that's because I was looking at the Recent Changes, but it's only happening on the main page. On the other wikis the main page stayed broken the longest. So at least most of the way through fixing itself? Also the IP address in the screenshot is the same one that shows up for me, so this is probably a CloudFlare issue. I'll reopen #425.

**Comment by mjsweet130** [comment]
Hey, @codynguyen1116 what further information are you looking for from me?

**Comment by codynguyen1116** [comment]
@mjsweet130 Hey, I apologize, you don't actually have to provide any more information! I was going to ask you about what web browser version and OS you were using but turns out they're irrelevant ot his situation. Thanks for asking though :)

@MtMNC I wish I could help but I'm unfamiliar with CloudFlare and how it functions, nor am I knowledgeable on servers heheh :P Would you able to research this weekend (or when you have time) on what's going on? This priority is a high issue and I'm betting this has actually going far longer than #425 was reported. Anonymous users deserve just as a good as an experience as signed in users, and we're just driving our own traffic and potential for community growth away. _Note_: I'll research up too myself don't worry about that, although I'm just not sure if I'll be able to help as much

**Comment by codynguyen1116** [comment]
Nevermind guys, it's working functionally now :) I tested it today and it's no longer an issue. I'm closing it, however @MTMNC, @mjsweet130, if it's still an issue, feel free to re-open (or comment and request for re-open). Thanks!

**Comment by ALittleSlow** [comment]
Thanks!
