### ISSUE TITLE
New blog system

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#444]
This issue is for discussing the new blog system that will replace the BlogPage extension. I'm marking down this for Q1 2016, which gives us 2 good months to get this from development to production phase! Hopefully that's enough time (it should be), and hopefully it's motivating enough for us to be able to get things done. :+1:

Feel free to edit this top comment to make check-lists for functions of the new system.

**Comment by mary-kate** [comment]
CC'ing myself on this since this seems interesting...

Some quick thoughts/questions:
1. "[...] that will *replace* the BlogPage extension" -- why? I'm aware that BlogPage is hardly perfect and has some, shall we say, *interesting* pieces of code left behind by the original developers, but I firmly believe in not reinventing the wheel.
2. 2 months might not be enough. Maybe for an extremely bare-bones prototype, but on the other hand, there's already BlogPage which is slightly more than a bare-bones prototype, so...yeah. MediaWiki is not WordPress and that -- I hope -- isn't the goal here either.

**Comment by UltrasonicNXT** [comment]
Gotta say I agree, might as well improve BlogPage rather than build a new one IMO

**Comment by codynguyen1116** [comment]
Hmm I see what you mean. I mean there's been a bunch of more iterated tests for BlogPage too. If it's really easier to manage then we can add it back to the wiki, although I've heard arguments for both side so I'm not too sure

**Comment by georgebarnick** [comment]
Honestly we don't need an extension to manage blogs though. We have SMW and all we need is a simple page creation tool to let people easily make a blog post (which will be built into the tool I'm already making to let people easily make <i>any</i> page) and from there the only other thing needed is some simple SMW properties to allow people to find blogs easier, whether it by by author or whatever. Much better and simpler than what BlogPage takes a whole extension to do in just a few SMW properties. This isn't a replacement to the BlogPage extension. BlogPage extension will still exist, Brickimedia just won't be using it. It's not necessary to have and causes more problems and bugs than is worth it.

**Comment by NovaFlare** [comment]
@georgebarnick: [already made one] (http://en.brickimedia.org/wiki/Special:BlankPage/newblog) about 24 hrs ago. I figured it'd make more sense to have a separate page- I thought it'd be less confusing for people who just want to make a blog. I was told SMW was disabled in most namespaces to save resources, but I don't really have any idea how to do anything without smw (the best I could get is seen on Cody's talk page on en).
