### ISSUE TITLE
Option to block PMs from a user

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#447]
There should be an option to block a user's PM. You know, in case someone's getting annoying? :P

**Comment by georgebarnick** [comment]
IMO the easiest option is to ignore them and/or tell them to stop. If they're trolling or harassing via PM, they should be reported and probably blocked from chat altogether.

**Comment by codynguyen1116** [comment]
Hmm so you're saying that method would cause less chaos then blocking a user PM (which now that I think about it seems a bit passive aggressive). I see what you mean :+1: 

Maybe we could just make a block PM feature a variable, and wikis can choose `true` if they want to enable it and `false` if they want to disable, and the default value would be `false`. This feature isn't actually really in dire need, just an idea that came to my head. Obviously there's lots of other things that are of at much higher priority, so this doesn't have to be done.

**Comment by NovaFlare** [comment]
Wouldn't be a bad feature to have in the long run, but I'd say it's a lot of work for NXT and it's not exactly a vital improvement, so it'd be a very low priority. As far as I know, there haven't been any real issues in chat in a very long time, and they can be dealt with easily by Meiko's method

**Comment by chriscook18** [comment]
I thought I'd commented on this - but, basically, there isn't too much demand for it right now, so its not a high priority thing. There is little disruption in chat, and if someone is PM-harassing, it is no longer one persons word vs another since functionaries have access to the PM log, and they are probably doing something block worthy. 

But not a bad feature idea in general, just not of high priority like Nova says.

**Comment by codynguyen1116** [comment]
Putting this on hold for now

**Comment by codynguyen1116** [comment]
Not a needed function as of now and not very important so I'm closing
