### ISSUE TITLE
Can't send a comment as an anon with an external link

### ISSUE THREAD

**Issue by SamanthaNguyen** [Brickimedia/brickimedia#472]
I'm not able to send a comment as an anon with an external link inside the comment, tested it on multiple browsers.

**Comment by mary-kate** [comment]
"It's not a bug, it's a feature!"

Quite literally, I'm afraid. To be specific, it's a rather cheap, mowing-your-lawn-with-a-tank sorta anti-spam measure.

When you press the "Comment" button, an AJAX request is sent. This call is handled by `/extensions/Comments/api/CommentSubmit.api.php`, which, when the comment text is _not_ empty, calls `CommentFunctions::isSpam()` on the supplied comment for users who do not have the `commentadmin` user right. `CommentFunctions::isSpam()` is a simple wrapper around the core MW anti-spam globals `$wgSpamRegex` and `$wgSummarySpamRegex` (but there's also a hook, `Comments::isSpam` which could be hooked into AbuseFilter or somesuch to allow AF to perform actions on comments).

Most sites don't define the spam regex globals, so this test will likely pass. After that, the next test is "does the comment contain links (`CommentFunctions::haveLinks()`) and does the user have the appropriate permission (`commentlinks`) to post links?".
By default, everyone (`*`) can add comments (`$wgGroupPermissions['*']['comment'] = true;`) but only `autoconfirmed` users can post comments containing links (`$wgGroupPermissions['autoconfirmed']['commentlinks'] = true;`). If you do not have this user right and you try to post a comment containing external links, you should be shown the `MediaWiki:Comments-links-are-forbidden` message (the default text of which is "External links in comments are forbidden!").

If we want to "fix" this, the "fix" is literally one line in the appropriate configuration file, probably `LocalSettings_ext.php`: `$wgGroupPermissions['*']['commentlinks'] = true;` but I'm not sure if this is something we want, given the recent concerns over social tools admin features increasing the admin workload. Given Brickipedia's popularity, I'm pretty confident that doing this would increase admin workload for real, because chances are it wouldn't take very long for spambots to figure out that they can use the comments boxes to send their crap.

**Comment by codynguyen1116** [comment]
(pinging @chriscook18)
Interesting, I didn't know that it was actually a configurable user right. :P I didn't get the i18n message "comments-links-are-forbidden" however, I would click the button and nothing would change, nor did anything pop up.

**Comment by mary-kate** [comment]
@codynguyen1116 Thanks for the additional details, I've verified the problem and fixed it upstream ([gerrit changeset #279593](https://gerrit.wikimedia.org/r/#/c/279593/)). Now the only thing left here is to deploy the fix.

**Comment by codynguyen1116** [comment]
@georgebarnick Can you push this commit to the server?

**Comment by neoncitylights** [comment]
Superseded by https://phabricator.wikimedia.org/T143512
