### ISSUE TITLE
Preferences tabs aren't displaying correctly in Refreshed

### ISSUE THREAD

**Issue by SamanthaNguyen** [Brickimedia/brickimedia#473]
Preferences tabs aren't displaying on Refreshed skin, but are in other skins such as Vector, and DeepSea.

![image](https://cloud.githubusercontent.com/assets/4723983/14066549/04e45d3a-f412-11e5-9511-1104506569c3.png)
![image](https://cloud.githubusercontent.com/assets/4723983/14066544/dcf7a7b4-f411-11e5-8e6b-934c7bf71760.png)
![image](https://cloud.githubusercontent.com/assets/4723983/14066547/f61ccfd0-f411-11e5-84c8-4216cfd09be9.png)

**Comment by chriscook18** [comment]
Can confirm that this has happened for at the very least the last few
months, if not further back - I can't recall a time when it wasn't doing
that in.
On 27 Mar 2016 17:50, "Cody Nguyen" <notifications@github.com> wrote:
>
> Preferences tabs aren't displaying on Refreshed skin, but are in other
skins such as Vector, and DeepSea.

**Comment by mary-kate** [comment]
First the historical stuff, because I like history and sometimes it's useful to know it, too! Nowadays there's a ResourceLoader module called `mediawiki.special.preferences`, which, as the name might suggest, is loaded on Special:Preferences. For whatever reason, this module _still_ contains only some very basic styles, so just like years ago, all skins need to implement (read: copy-paste from MonoBook) the "default" styling of `#preftoc` themselves. Refreshed didn't, so the tabs weren't rendering the way we're used to. Now (Brickimedia/Refreshed@cbdb1d6) they do, so all that's left here is to deploy the fix.

**Comment by LegoFan4000** [comment]
Its like that for me too.

**Comment by codynguyen1116** [comment]
@georgebarnick Can you push this commit to the server also? Thanks :)

**Comment by neoncitylights** [comment]
Superseded by https://phabricator.wikimedia.org/T143512 (update Refreshed extension)
